### ISSUE TITLE
`requestOptions` are not added to the DeepL request

### ISSUE THREAD

**Issue by silllli** [kirby-tools/kirby-content-translator#19]
The `requestOptions` set in the Kirby config are not added to the DeepL request. The problem is [in this line](https://github.com/kirby-tools/kirby-content-translator/blob/e7928de17d18b3aaf7200788346c57031a99592f/src/classes/ContentTranslator/DeepL.php#L46) which needs to use a case-sensitive property name: `$kirby->option('johannschopplich.content-translator.DeepL.requestOptions', [])`.

**Comment by johannschopplich** [comment]
Thanks! Fixed in https://github.com/kirby-tools/kirby-content-translator/commit/79f74affa0e87ae9f0b119591e53d2576f5e26b8.
Release is on its way.

**Comment by silllli** [comment]
Oh just noticed it’s still not quite fixed … you are now reading the `johannschopplich.content-translator.Deepl.requestOptions` option whereas it should be `johannschopplich.content-translator.DeepL.requestOptions` (with a capital L).
